### ISSUE TITLE
game ends when i press x

### ISSUE THREAD

**Issue by TonyNashe** [RamsesCaesar/CatAmongBats#29] opened 2021-05-30 20:15 UTC
is this intentional? 

When x is pressed all bats are defeated

**Comment by RamsesCaesar** [comment] 2021-05-31 07:59
Thank you for the feedback!  
The bug is caused by a debug feature that wasn't deactivated for the last release.
It will be fixed in the next release.

**Comment by RamsesCaesar** [comment] 2021-05-31 08:09
Fixed with in a hotfix on main.

**Closed by RamsesCaesar** 2021-05-31 08:09 UTC
